[package]
name = "bilibili-api-rs"
version.workspace = true
edition.workspace = true

[dependencies]
bili-auth = {  path = "bili-auth" }
bili-core = { path = "bili-core" }
bili-login = {path = "bili-login" }
bili-service = {  path = "bili-service" }
bili-video = {  path = "bili-video" }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[workspace]
members = ["bili-account","bili-auth","bili-core", "bili-derive", "bili-login", "bili-service", "bili-video"]

[workspace.package]
version = "0.4.0"
edition = "2024"

[workspace.dependencies]
derive_more = { version = "2.1.1", features = ["full"] }
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
serde-aux = "4.7.0"
serde_repr = "0.1.20"
serde_qs = "0.15.0"

[dev-dependencies]
anyhow = "1.0.100"
futures-util = "0.3.31"
reqwest = { version = "0.13.1", features = ["cookies", "json", "stream"] }
tempfile = "3.25.0"
tokio = { version = "1.49.0", features = ["full"] }
