[package]
name = "bili-account"
version.workspace = true
edition.workspace = true

[dependencies]
bili-core = { path = "../bili-core" }
chrono = { version = "0.4.43", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde-aux.workspace = true
serde_repr.workspace = true

[dev-dependencies]
bili-service = { path = "../bili-service" }
bili-test-utils = { path = "../bili-test-utils" }
reqwest = { version = "0.13.3", features = ["cookies"] }
serde_json = "1.0.149"
tokio = { version = "1.52.3", features = ["full"] }
