[package]
name = "bili-account"
version.workspace = true
edition.workspace = true

[dependencies]
bili-core = { version = "0.1.0", path = "../bili-core" }
chrono = { version = "0.4.43", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde-aux.workspace = true
serde_repr.workspace = true

[dev-dependencies]
serde_json = "1.0.149"
